=begin
This Vagrantfile builds some virtual machine on your machine to make clusters and/or replica-sets.

machine deployment design is:
@startuml
node your_computer as host

node 192.168.57.17 as controller {
}

node 192.168.57.18 as host1 {
  database mysql_master
  database redis01

  node monitor_agent01 #skyblue
}

node 192.168.57.19 as  host2 {
  database mysql_slave
  database redis02

  node monitor_agent02 #skyblue
}

node 192.168.57.20 as host3 {
  database redis03

  node monitor #skyblue
  database for_monitor #skyblue
  node monitor_agent03 #skyblue
}

host - controller: ./ synced to /vagrant

controller --> host1: ansible on ssh
controller --> host2: ansible on ssh
controller --> host3: ansible on ssh

' replication example
mysql_master <-- mysql_slave

' clustering example
redis01 -- redis02
redis01 -- redis03
redis02 - redis03

' monitor
for_monitor <- monitor: send data
monitor <- monitor_agent01: send data
monitor <- monitor_agent02: send data
monitor <- monitor_agent03: send data
@enduml
=end

Vagrant.configure("2") do |config|

  (1..3).each do |i|
    machine_name = "host#{i}"
    host_address = 17 + i
    ip_address = "192.168.57.#{host_address}"

    config.vm.define machine_name do |machine|

      machine.vm.box = "ubuntu/xenial64"
      machine.vm.hostname = "#{machine_name}"
      machine.vm.network :private_network,
                        ip: ip_address
    end
  end

  config.vm.define "controller", primary: true do |mchine|
    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "controller"
    config.vm.network :private_network,
                      ip: "192.168.57.17"

    # provision
    config.vm.synced_folder ".", "/vagrant",
                            id: "provision",
                            mount_options: %w(dmode=775 fmode=664)
    # directory root is `/vagrant`
    config.vm.provision :ansible_local,
                        playbook: "site.yml",
                        inventory_path: "vagrant",
                        limit: "all",
                        galaxy_role_file: "requirements.yml",
                        galaxy_roles_path: "galaxy_roles",
                        verbose: "-vv"
  end

end
